hbsi_file_path: inputHBSIfiles/DAVCLanSettings.hbsi
component_name: DESettings
output_config_folder: output
entities:
   component: CDataExtractorSettingsComponent
   logic: CDataExtractorSettingsLogic
   impl: CDAVCLanSettingsImpl
   onoff: CSettingsSPOnOffClientImpl
   onoffStub: CSPOnOffClientStub
   client: CAVCLanSettingsProtocolMessagingClient
   clientBase: CAVCLanProtocolMessagingClientBase
   command_specific_logic: 
      file_name: CCommandSpecificLogic
      namespace: AVCLanDESettingsCommands
   commands:
      file_name: DESettingsCommandTypes
      namespace: AVCLanDESettingsCommandTypes
   types : AVCLanProtocolMessagingTypes
   templ_class: 
      ser: TAVCLanSerializationCmd
      deser: TAVCLanDeserializationCmd